### ISSUE TITLE
Update to the new version

### ISSUE THREAD

**Issue by brog-io** [MianReplicate/Attack-Through-Grass#1]
Could you update this to the new version?

**Comment by MianReplicate** [comment]
Does it not work on the latest version? If not, please send a log.

**Comment by brog-io** [comment]
Wait my bad, messed something up on my side

**Comment by chrrybmb64** [comment]
On Modrinth it says the mod is only compatible with up to 1.21.3, if it works on 1.21.4 it should to be marked as supported.

**Comment by MianReplicate** [comment]
I would mark it as compatible but honestly I don't really have the motivation/time to constantly update my mod versions when Minecraft gets an update + I don't actually know if it does work, I'm just assuming so. With ATG, I assume that it works fine since it changes very little in the code. I may mark it as compatible later but that's when I feel motivated to.
